name: notam-map

services:
  webserver:
    image: localhost/notammap/frontend-webserver
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: notamdata
        target: /usr/share/caddy/notamdata
        read_only: true
        volume:
          nocopy: true
    depends_on:
      - tmsproxy

  extractor:
    image: localhost/notammap/notamextractor
    volumes:
      - notamdata:/data

  tmsproxy:
    image: ghcr.io/bitfexl/tmsproxy:latest
    volumes:
      - ./config/tmsconfig:/config:ro
      - tilecache:/tile-cache
    expose:
      - "80"

volumes:
  notamdata:
  tilecache: