name: notam-map

services:
  webserver:
    build:
      context: ./notammap
      args:
        - OPENAIP_TILE_LAYER_URL=/tiles/openaip/{z}/{x}/{y}
        - SATELLITE_TILE_LAYER_URL=/tiles/satellite/{z}/{x}/{y}
        # - INJECT_HEAD="<script> /* TODO inject analytics script */ </script>"
    ports:
      - "8080:80"
    volumes:
      - type: volume
        source: notamdata
        target: /usr/share/caddy/notamdata
        read_only: true
        volume:
          nocopy: true
    depends_on:
      - tmsproxy

  extractor:
    build: ./notamextractor
    volumes:
      - notamdata:/data

  tmsproxy:
    image: ghcr.io/bitfexl/tmsproxy:latest
    volumes:
      - ./config/tmsconfig:/config:ro
      - tilecache:/tile-cache
    expose:
      - "80"

volumes:
  notamdata:
  tilecache: