%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
%dev.quarkus.hibernate-orm.log.sql=false

%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=notammap
%dev.quarkus.datasource.password=pammaton
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/notammap

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.mapping.timezone.default-storage=NORMALIZE_UTC
quarkus.hibernate-orm.jdbc.timezone=UTC

quarkus.analytics.disabled=true
quarkus.banner.enabled=false